lwr:
  # CONTROLLERS USED IN THE EXAMLE
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # THIS CONFIGURATION IS ACTUALLY SENDING TAU = K*Q
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - lwr_0_joint
      - lwr_1_joint
      - lwr_2_joint
      - lwr_3_joint
      - lwr_4_joint
      - lwr_5_joint
      - lwr_6_joint

  stiffness_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - lwr_0_joint
      - lwr_1_joint
      - lwr_2_joint
      - lwr_3_joint
      - lwr_4_joint
      - lwr_5_joint
      - lwr_6_joint
    #constraints:
      #lwr_0_joint: 
        #goal:0.02
      #lwr_1_joint: 
        #goal:0.02
      #lwr_2_joint: 
        #goal:0.02
      #lwr_3_joint: 
        #goal:0.02
      #lwr_4_joint: 
        #goal:0.02
      #lwr_5_joint: 
        #goal:0.02
      #lwr_6_joint: 
        #goal:0.02

      #goal_time: 0.5                   # Override default
      #stopped_velocity_tolerance: 0.02 # Override default

    #gains:
      #lwr_0_joint: {p: 1000,  i: 0, d: 0, i_clamp: 0.5}
      #lwr_1_joint: {p: 800,  i: 0, d: 0, i_clamp: 0.5}
      #lwr_2_joint: {p: 700,  i: 0, d: 0, i_clamp: 0.5}
      #lwr_3_joint: {p: 500,  i: 0, d: 0, i_clamp: 0.5}
      #lwr_4_joint: {p: 450,  i: 0, d: 0, i_clamp: 0.5}
      #lwr_5_joint: {p: 100,  i: 0, d: 0, i_clamp: 0.5}
      #lwr_6_joint: {p: 25,  i: 0, d: 0, i_clamp: 0.5}

## OTHER CUSTOM CONTROLLERS LEFT HERE AS EXAMPLES
  #   Joint Impedance Controllers
  JointImpedanceControl:
    type: lwr_controllers/JointImpedanceController
    root_name: lwr_base_link
    tip_name: lwr_7_link
    stiffness_gains: 300
    damping_gains: 0.7

  # Inverse Dynamics Controllers
  InverseDynamicsControl:
    type: lwr_controllers/InverseDynamicsController
    root_name: lwr_base_link
    tip_name: lwr_7_link

  # Computed Torque Controllers
  ComputedTorqueControl: 
    type: lwr_controllers/ComputedTorqueController
    root_name: lwr_base_link
    tip_name: lwr_7_link

  # One Task Inverse Kinematics
  OneTaskInverseKinematics: 
    type: lwr_controllers/OneTaskInverseKinematics
    root_name: lwr_base_link
    tip_name: lwr_7_link
    pid_lwr_0_joint: {p: 250,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_1_joint: {p: 220,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_2_joint: {p: 150,  i: 6, d: 20, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_3_joint: {p: 150,  i: 5, d: 12, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_4_joint: {p: 90,  i: 5, d: 10, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_5_joint: {p: 40,  i: 5, d: 7, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_6_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}

  # Multi Task Priority Inverse Kinematics
  MultiTaskPriorityInverseKinematics: 
    type: lwr_controllers/MultiTaskPriorityInverseKinematics
    root_name: lwr_base_link
    tip_name: lwr_7_link
    pid_lwr_0_joint: {p: 250,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_1_joint: {p: 220,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_2_joint: {p: 150,  i: 6, d: 20, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_3_joint: {p: 150,  i: 5, d: 12, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_4_joint: {p: 90,  i: 5, d: 10, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_5_joint: {p: 40,  i: 5, d: 7, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_lwr_6_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}

  # One Task Inverse Dynamics JL
  OneTaskInverseDynamicsJL: 
    type: lwr_controllers/OneTaskInverseDynamicsJL
    root_name: lwr_base_link
    tip_name: lwr_7_link

  # Multi Task Priority Inverse Dynamics
  MultiTaskPriorityInverseDynamics: 
    type: lwr_controllers/MultiTaskPriorityInverseDynamics
    root_name: lwr_base_link
    tip_name: lwr_7_link

  # Minimum Effort Inverse Dynamics
  MinimumEffortInverseDynamics: 
    type: lwr_controllers/MinimumEffortInverseDynamics
    root_name: lwr_base_link
    tip_name: lwr_7_link

  # Backstepping Controller
  BacksteppingController: 
    type: lwr_controllers/BacksteppingController
    root_name: lwr_base_link
    tip_name: lwr_7_link

  # Dynamic Sliding Mode Controller
  DynamicSlidingModeController: 
     type: lwr_controllers/DynamicSlidingModeController
     root_name: lwr_base_link
     tip_name: lwr_7_link

  # Dynamic Sliding Mode Controller Task Space
  DynamicSlidingModeControllerTaskSpace: 
     type: lwr_controllers/DynamicSlidingModeControllerTaskSpace
     root_name: lwr_base_link
     tip_name: lwr_7_link
